version: "3.1"

services:
  postgres:
    build: ./database
    environment:
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: hospe
      POSTGRES_DB: hospe
    volumes:
      - hospe-postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: charuka@protonmail.com
      PGADMIN_DEFAULT_PASSWORD: dbpassword
    ports:
      - 5433:80
    volumes:
      - ./database/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  hospe-postgres:
