version: "3.1"

services:
  db:
    image: postgres:13.3
    restart: unless-stopped
    ports:
      - 7000:5432
    environment:
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: hospe
      POSTGRES_DB: hospe
    volumes:
      - hospe-vol:/var/lib/postgresql/data

volumes:
  hospe-vol:
